---
- include_role:
    name: andrewrothstein.systemd_service
  vars:
    systemd_service_activate: '{{ node_exporter_activate }}'
    systemd_service_def:
      name: node_exporter
      description: Prometheus node_exporter
      exe: /usr/local/bin/node_exporter
      args: '$NODE_EXPORTER_ARGS'
      env:
        dir: /etc/node_exporter
        filename: env
        data:
          NODE_EXPORTER_ARGS: '{{ node_exporter_args | default("") }}'
      start_limit:
        interval: 5
        burst: 10
      restart:
        policy: always
        sec: 120
      after:
        - syslog.target
        - network.target
      wanted_by:
        - multi-user.target
