---
- name: mkdir {{ node_exporter_systemd_service.env.dir }}
  become: yes
  become_user: root
  file:
    path: '{{ node_exporter_systemd_service.env.dir }}'
    mode: 0700
    state: directory
    owner: '{{ node_exporter_service_def.user | default("root") }}'
    group: '{{ node_exporter_service_def.group | default("root") }}'
- name: templatizing environment
  become: yes
  become_user: root
  template:
    src: node_exporter.env.j2
    dest: '{{ node_exporter_fq_env_file }}'
    mode: 0600
    owner: '{{ node_exporter_service_def.user | default("root") }}'
    group: '{{ node_exporter_service_def.group | default("root") }}'
  notify: node_exporter_restart
